"""empty message

Revision ID: 094e4ddeb4bd
Revises: 4abc26ba61c3
Create Date: 2024-06-30 03:09:00.753852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094e4ddeb4bd'
down_revision: Union[str, None] = '4abc26ba61c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
