"""empty message

Revision ID: 22617cde7280
Revises: 80e5abb55ae9
Create Date: 2024-06-30 02:52:01.498567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22617cde7280'
down_revision: Union[str, None] = '80e5abb55ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('id_customer', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales', 'custumers', ['id_customer'], ['id'])
    op.create_foreign_key(None, 'sales', 'stores', ['id_store'], ['id'])
    op.drop_column('sales', 'id_custumer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('id_custumer', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'id_customer')
    # ### end Alembic commands ###
