"""empty message

Revision ID: 86b9d21a4cd8
Revises: 
Create Date: 2024-07-09 20:42:16.138404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b9d21a4cd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_customers_cpf'), 'customers', ['cpf'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('customer_store_association',
    sa.Column('id_store', sa.UUID(), nullable=False),
    sa.Column('id_customer', sa.UUID(), nullable=False),
    sa.Column('account_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id'], name='fk_association_customer'),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id'], name='fk_association_store'),
    sa.PrimaryKeyConstraint('id_store', 'id_customer'),
    sa.UniqueConstraint('id_store', 'id_customer')
    )
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_customer', sa.UUID(), nullable=True),
    sa.Column('id_store', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id'], name='fk_sale_customer'),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id'], name='fk_sale_store'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('cashbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('redeem', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id_sale', sa.UUID(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_sale'], ['sales.id'], name='fk_cashback_sales'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashbacks')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('customer_store_association')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_cpf'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
