"""empty message

Revision ID: ab45fea108f8
Revises: 90abe4bf37b6
Create Date: 2024-06-30 02:37:52.853518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab45fea108f8'
down_revision: Union[str, None] = '90abe4bf37b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cashbacks_id_sale_fkey', 'cashbacks', type_='foreignkey')
    op.create_foreign_key(None, 'cashbacks', 'sales', ['id_sale'], ['id'])
    op.create_unique_constraint(None, 'custumer_store_association', ['id_store', 'id_custumer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custumer_store_association', type_='unique')
    op.drop_constraint(None, 'cashbacks', type_='foreignkey')
    op.create_foreign_key('cashbacks_id_sale_fkey', 'cashbacks', 'custumers', ['id_sale'], ['id'])
    # ### end Alembic commands ###
