"""empty message

Revision ID: ebad3722610b
Revises: 
Create Date: 2024-06-28 19:27:12.233712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebad3722610b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('redeem', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custumers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_custumers_cpf'), 'custumers', ['cpf'], unique=True)
    op.create_index(op.f('ix_custumers_id'), 'custumers', ['id'], unique=False)
    op.create_index(op.f('ix_custumers_name'), 'custumers', ['name'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_table('costumer_store',
    sa.Column('id_store', sa.UUID(), nullable=False),
    sa.Column('id_custumer', sa.UUID(), nullable=False),
    sa.Column('account_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_custumer'], ['custumers.id'], ),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id_store', 'id_custumer')
    )
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custumer_buyer', sa.UUID(), nullable=True),
    sa.Column('seller_store', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('percentage_cash', sa.Float(), nullable=True),
    sa.Column('cash_generated', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cash_generated'], ['cashbacks.id'], ),
    sa.ForeignKeyConstraint(['custumer_buyer'], ['custumers.id'], ),
    sa.ForeignKeyConstraint(['seller_store'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('costumer_store')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_custumers_name'), table_name='custumers')
    op.drop_index(op.f('ix_custumers_id'), table_name='custumers')
    op.drop_index(op.f('ix_custumers_cpf'), table_name='custumers')
    op.drop_table('custumers')
    op.drop_table('cashbacks')
    # ### end Alembic commands ###
