"""empty message

Revision ID: ee978ef5b3e6
Revises: 
Create Date: 2024-06-29 01:28:59.829947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee978ef5b3e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custumer_store_association',
    sa.Column('id_store', sa.UUID(), nullable=False),
    sa.Column('id_custumer', sa.UUID(), nullable=False),
    sa.Column('account_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_custumer'], ['custumers.id'], ),
    sa.ForeignKeyConstraint(['id_store'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id_store', 'id_custumer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custumer_store_association')
    # ### end Alembic commands ###
