"""empty message

Revision ID: f4abb7ec6c02
Revises: 9108a2275f59
Create Date: 2024-06-30 03:00:12.971918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4abb7ec6c02'
down_revision: Union[str, None] = '9108a2275f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('id_custumer', sa.UUID(), nullable=True))
    op.drop_constraint('sales_id_customer_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'custumers', ['id_custumer'], ['id'])
    op.drop_column('sales', 'id_customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('id_customer', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_id_customer_fkey', 'sales', 'custumers', ['id_customer'], ['id'])
    op.drop_column('sales', 'id_custumer')
    # ### end Alembic commands ###
